config/routes.rb
Rails.application.routes.draw do
  resources :home_appliances
  resources :headphones
  resources :televisions
  resources :laptops
  resources :cell_phones
  root "cell_phones#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/headphone.rb
class Headphone < ApplicationRecord
end

app/controllers/headphones_controller.rb
class HeadphonesController < ApplicationController
  before_action :set_headphone, only: %i[ show edit update destroy ]

  # GET /headphones or /headphones.json
  def index
    @headphones = Headphone.all
  end

  # GET /headphones/1 or /headphones/1.json
  def show
  end

  # GET /headphones/new
  def new
    @headphone = Headphone.new
  end

  # GET /headphones/1/edit
  def edit
  end

  # POST /headphones or /headphones.json
  def create
    @headphone = Headphone.new(headphone_params)

    respond_to do |format|
      if @headphone.save
        format.html { redirect_to @headphone, notice: "Headphone was successfully created." }
        format.json { render :show, status: :created, location: @headphone }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @headphone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /headphones/1 or /headphones/1.json
  def update
    respond_to do |format|
      if @headphone.update(headphone_params)
        format.html { redirect_to @headphone, notice: "Headphone was successfully updated." }
        format.json { render :show, status: :ok, location: @headphone }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @headphone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /headphones/1 or /headphones/1.json
  def destroy
    @headphone.destroy
    respond_to do |format|
      format.html { redirect_to headphones_url, notice: "Headphone was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_headphone
      @headphone = Headphone.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def headphone_params
      params.require(:headphone).permit(:LaptopName, :Memory, :Condition, :Location, :Price)
    end
end

app/helpers/headphones_helper.rb
module HeadphonesHelper
end

app/views/headphones/_form.html.erb
<%= form_with(model: headphone, local: true) do |form| %>
  <% if headphone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(headphone.errors.count, "error") %> prohibited this headphone from being saved:</h2>

      <ul>
        <% headphone.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :LaptopName %>
    <%= form.text_field :LaptopName %>
  </div>

  <div class="field">
    <%= form.label :Memory %>
    <%= form.text_field :Memory %>
  </div>

  <div class="field">
    <%= form.label :Condition %>
    <%= form.text_field :Condition %>
  </div>

  <div class="field">
    <%= form.label :Location %>
    <%= form.text_field :Location %>
  </div>

  <div class="field">
    <%= form.label :Price %>
    <%= form.text_field :Price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/headphones/edit.html.erb
<h1>Editing Headphone</h1>

<%= render 'form', headphone: @headphone %>

<%= link_to 'Show', @headphone %> |
<%= link_to 'Back', headphones_path %>

app/views/headphones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Headphones</h1>

<table>
  <thead>
    <tr>
      <th>Laptopname</th>
      <th>Memory</th>
      <th>Condition</th>
      <th>Location</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @headphones.each do |headphone| %>
      <tr>
        <td><%= headphone.LaptopName %></td>
        <td><%= headphone.Memory %></td>
        <td><%= headphone.Condition %></td>
        <td><%= headphone.Location %></td>
        <td><%= headphone.Price %></td>
        <td><%= link_to 'Show', headphone %></td>
        <td><%= link_to 'Edit', edit_headphone_path(headphone) %></td>
        <td><%= link_to 'Destroy', headphone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Headphone', new_headphone_path %>

app/views/headphones/new.html.erb
<h1>New Headphone</h1>

<%= render 'form', headphone: @headphone %>

<%= link_to 'Back', headphones_path %>

app/views/headphones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Laptopname:</strong>
  <%= @headphone.LaptopName %>
</p>

<p>
  <strong>Memory:</strong>
  <%= @headphone.Memory %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @headphone.Condition %>
</p>

<p>
  <strong>Location:</strong>
  <%= @headphone.Location %>
</p>

<p>
  <strong>Price:</strong>
  <%= @headphone.Price %>
</p>

<%= link_to 'Edit', edit_headphone_path(@headphone) %> |
<%= link_to 'Back', headphones_path %>