config/routes.rb
Rails.application.routes.draw do
  resources :home_appliances
  resources :headphones
  resources :televisions
  resources :laptops
  resources :cell_phones
  root "cell_phones#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/home_appliance.rb
class HomeAppliance < ApplicationRecord
end

app/controllers/home_appliances_controller.rb
class HomeAppliancesController < ApplicationController
  before_action :set_home_appliance, only: %i[ show edit update destroy ]

  # GET /home_appliances or /home_appliances.json
  def index
    @home_appliances = HomeAppliance.all
  end

  # GET /home_appliances/1 or /home_appliances/1.json
  def show
  end

  # GET /home_appliances/new
  def new
    @home_appliance = HomeAppliance.new
  end

  # GET /home_appliances/1/edit
  def edit
  end

  # POST /home_appliances or /home_appliances.json
  def create
    @home_appliance = HomeAppliance.new(home_appliance_params)

    respond_to do |format|
      if @home_appliance.save
        format.html { redirect_to @home_appliance, notice: "Home appliance was successfully created." }
        format.json { render :show, status: :created, location: @home_appliance }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @home_appliance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /home_appliances/1 or /home_appliances/1.json
  def update
    respond_to do |format|
      if @home_appliance.update(home_appliance_params)
        format.html { redirect_to @home_appliance, notice: "Home appliance was successfully updated." }
        format.json { render :show, status: :ok, location: @home_appliance }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @home_appliance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /home_appliances/1 or /home_appliances/1.json
  def destroy
    @home_appliance.destroy
    respond_to do |format|
      format.html { redirect_to home_appliances_url, notice: "Home appliance was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home_appliance
      @home_appliance = HomeAppliance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def home_appliance_params
      params.require(:home_appliance).permit(:LaptopName, :Memory, :Condition, :Location, :Price)
    end
end

app/helpers/home_appliances_helper.rb
module HomeAppliancesHelper
end

app/views/home_appliances/_form.html.erb
<%= form_with(model: home_appliance, local: true) do |form| %>
  <% if home_appliance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home_appliance.errors.count, "error") %> prohibited this home_appliance from being saved:</h2>

      <ul>
        <% home_appliance.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :LaptopName %>
    <%= form.text_field :LaptopName %>
  </div>

  <div class="field">
    <%= form.label :Memory %>
    <%= form.text_field :Memory %>
  </div>

  <div class="field">
    <%= form.label :Condition %>
    <%= form.text_field :Condition %>
  </div>

  <div class="field">
    <%= form.label :Location %>
    <%= form.text_field :Location %>
  </div>

  <div class="field">
    <%= form.label :Price %>
    <%= form.text_field :Price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/home_appliances/edit.html.erb
<h1>Editing Home Appliance</h1>

<%= render 'form', home_appliance: @home_appliance %>

<%= link_to 'Show', @home_appliance %> |
<%= link_to 'Back', home_appliances_path %>

app/views/home_appliances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Home Appliances</h1>

<table>
  <thead>
    <tr>
      <th>Laptopname</th>
      <th>Memory</th>
      <th>Condition</th>
      <th>Location</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @home_appliances.each do |home_appliance| %>
      <tr>
        <td><%= home_appliance.LaptopName %></td>
        <td><%= home_appliance.Memory %></td>
        <td><%= home_appliance.Condition %></td>
        <td><%= home_appliance.Location %></td>
        <td><%= home_appliance.Price %></td>
        <td><%= link_to 'Show', home_appliance %></td>
        <td><%= link_to 'Edit', edit_home_appliance_path(home_appliance) %></td>
        <td><%= link_to 'Destroy', home_appliance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Home Appliance', new_home_appliance_path %>

app/views/home_appliances/new.html.erb
<h1>New Home Appliance</h1>

<%= render 'form', home_appliance: @home_appliance %>

<%= link_to 'Back', home_appliances_path %>

app/views/home_appliances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Laptopname:</strong>
  <%= @home_appliance.LaptopName %>
</p>

<p>
  <strong>Memory:</strong>
  <%= @home_appliance.Memory %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @home_appliance.Condition %>
</p>

<p>
  <strong>Location:</strong>
  <%= @home_appliance.Location %>
</p>

<p>
  <strong>Price:</strong>
  <%= @home_appliance.Price %>
</p>

<%= link_to 'Edit', edit_home_appliance_path(@home_appliance) %> |
<%= link_to 'Back', home_appliances_path %>