config/routes.rb
Rails.application.routes.draw do
  resources :home_appliances
  resources :headphones
  resources :televisions
  resources :laptops
  resources :cell_phones
  root "cell_phones#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/television.rb
class Television < ApplicationRecord
end

app/controllers/televisions_controller.rb
class TelevisionsController < ApplicationController
  before_action :set_television, only: %i[ show edit update destroy ]

  # GET /televisions or /televisions.json
  def index
    @televisions = Television.all
  end

  # GET /televisions/1 or /televisions/1.json
  def show
  end

  # GET /televisions/new
  def new
    @television = Television.new
  end

  # GET /televisions/1/edit
  def edit
  end

  # POST /televisions or /televisions.json
  def create
    @television = Television.new(television_params)

    respond_to do |format|
      if @television.save
        format.html { redirect_to @television, notice: "Television was successfully created." }
        format.json { render :show, status: :created, location: @television }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @television.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /televisions/1 or /televisions/1.json
  def update
    respond_to do |format|
      if @television.update(television_params)
        format.html { redirect_to @television, notice: "Television was successfully updated." }
        format.json { render :show, status: :ok, location: @television }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @television.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /televisions/1 or /televisions/1.json
  def destroy
    @television.destroy
    respond_to do |format|
      format.html { redirect_to televisions_url, notice: "Television was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_television
      @television = Television.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def television_params
      params.require(:television).permit(:LaptopName, :Memory, :Condition, :Location, :Price)
    end
end

app/helpers/televisions_helper.rb
module TelevisionsHelper
end

app/views/televisions/_form.html.erb
<%= form_with(model: television, local: true) do |form| %>
  <% if television.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(television.errors.count, "error") %> prohibited this television from being saved:</h2>

      <ul>
        <% television.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :LaptopName %>
    <%= form.text_field :LaptopName %>
  </div>

  <div class="field">
    <%= form.label :Memory %>
    <%= form.text_field :Memory %>
  </div>

  <div class="field">
    <%= form.label :Condition %>
    <%= form.text_field :Condition %>
  </div>

  <div class="field">
    <%= form.label :Location %>
    <%= form.text_field :Location %>
  </div>

  <div class="field">
    <%= form.label :Price %>
    <%= form.text_field :Price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/televisions/edit.html.erb
<h1>Editing Television</h1>

<%= render 'form', television: @television %>

<%= link_to 'Show', @television %> |
<%= link_to 'Back', televisions_path %>

app/views/televisions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Televisions</h1>

<table>
  <thead>
    <tr>
      <th>Laptopname</th>
      <th>Memory</th>
      <th>Condition</th>
      <th>Location</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @televisions.each do |television| %>
      <tr>
        <td><%= television.LaptopName %></td>
        <td><%= television.Memory %></td>
        <td><%= television.Condition %></td>
        <td><%= television.Location %></td>
        <td><%= television.Price %></td>
        <td><%= link_to 'Show', television %></td>
        <td><%= link_to 'Edit', edit_television_path(television) %></td>
        <td><%= link_to 'Destroy', television, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Television', new_television_path %>

app/views/televisions/new.html.erb
<h1>New Television</h1>

<%= render 'form', television: @television %>

<%= link_to 'Back', televisions_path %>

app/views/televisions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Laptopname:</strong>
  <%= @television.LaptopName %>
</p>

<p>
  <strong>Memory:</strong>
  <%= @television.Memory %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @television.Condition %>
</p>

<p>
  <strong>Location:</strong>
  <%= @television.Location %>
</p>

<p>
  <strong>Price:</strong>
  <%= @television.Price %>
</p>

<%= link_to 'Edit', edit_television_path(@television) %> |
<%= link_to 'Back', televisions_path %>