config/routes.rb
Rails.application.routes.draw do
  resources :home_appliances
  resources :headphones
  resources :televisions
  resources :laptops
  resources :cell_phones
  root "cell_phones#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/laptop.rb
class Laptop < ApplicationRecord
end

app/controllers/laptops_controller.rb
class LaptopsController < ApplicationController
  before_action :set_laptop, only: %i[ show edit update destroy ]

  # GET /laptops or /laptops.json
  def index
    @laptops = Laptop.all
  end

  # GET /laptops/1 or /laptops/1.json
  def show
  end

  # GET /laptops/new
  def new
    @laptop = Laptop.new
  end

  # GET /laptops/1/edit
  def edit
  end

  # POST /laptops or /laptops.json
  def create
    @laptop = Laptop.new(laptop_params)

    respond_to do |format|
      if @laptop.save
        format.html { redirect_to @laptop, notice: "Laptop was successfully created." }
        format.json { render :show, status: :created, location: @laptop }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @laptop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /laptops/1 or /laptops/1.json
  def update
    respond_to do |format|
      if @laptop.update(laptop_params)
        format.html { redirect_to @laptop, notice: "Laptop was successfully updated." }
        format.json { render :show, status: :ok, location: @laptop }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @laptop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /laptops/1 or /laptops/1.json
  def destroy
    @laptop.destroy
    respond_to do |format|
      format.html { redirect_to laptops_url, notice: "Laptop was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_laptop
      @laptop = Laptop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def laptop_params
      params.require(:laptop).permit(:LaptopName, :Memory, :Condition, :Location, :Price)
    end
end

app/helpers/laptops_helper.rb
module LaptopsHelper
end

app/views/laptops/_form.html.erb
<%= form_with(model: laptop, local: true) do |form| %>
  <% if laptop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(laptop.errors.count, "error") %> prohibited this laptop from being saved:</h2>

      <ul>
        <% laptop.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :LaptopName %>
    <%= form.text_field :LaptopName %>
  </div>

  <div class="field">
    <%= form.label :Memory %>
    <%= form.text_field :Memory %>
  </div>

  <div class="field">
    <%= form.label :Condition %>
    <%= form.text_field :Condition %>
  </div>

  <div class="field">
    <%= form.label :Location %>
    <%= form.text_field :Location %>
  </div>

  <div class="field">
    <%= form.label :Price %>
    <%= form.text_field :Price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/laptops/edit.html.erb
<h1>Editing Laptop</h1>

<%= render 'form', laptop: @laptop %>

<%= link_to 'Show', @laptop %> |
<%= link_to 'Back', laptops_path %>

app/views/laptops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Laptops</h1>

<table>
  <thead>
    <tr>
      <th>Laptopname</th>
      <th>Memory</th>
      <th>Condition</th>
      <th>Location</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @laptops.each do |laptop| %>
      <tr>
        <td><%= laptop.LaptopName %></td>
        <td><%= laptop.Memory %></td>
        <td><%= laptop.Condition %></td>
        <td><%= laptop.Location %></td>
        <td><%= laptop.Price %></td>
        <td><%= link_to 'Show', laptop %></td>
        <td><%= link_to 'Edit', edit_laptop_path(laptop) %></td>
        <td><%= link_to 'Destroy', laptop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Laptop', new_laptop_path %>

app/views/laptops/new.html.erb
<h1>New Laptop</h1>

<%= render 'form', laptop: @laptop %>

<%= link_to 'Back', laptops_path %>

app/views/laptops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Laptopname:</strong>
  <%= @laptop.LaptopName %>
</p>

<p>
  <strong>Memory:</strong>
  <%= @laptop.Memory %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @laptop.Condition %>
</p>

<p>
  <strong>Location:</strong>
  <%= @laptop.Location %>
</p>

<p>
  <strong>Price:</strong>
  <%= @laptop.Price %>
</p>

<%= link_to 'Edit', edit_laptop_path(@laptop) %> |
<%= link_to 'Back', laptops_path %>